### PR TITLE
Fix iOS Build issue with #25

### LINKED ISSUE #25: iOS Build failed because of 'self.bridge' (easy to fix)
**Describe the bug**
When i tried to build, it shown. 
image

**Expected behavior**
Success to build

**Library Environment:**
 - OS: iOS
 - Version 0.4.1

Just use `self.bridge?.viewController` then it fixed.

### PR DESCRIPTION
**Pull request by leo6104**
Resolve #25

### CODE REVIEW

**Comment by rdlabo** [comment]
Thanks for pull request. In my environment(Xcode Version 12.4), I don't see that error.
But this change seems good, and work. So I will merge this pull request. Thanks.

( If it is possible, I want to know your xcode version)

**Comment by rdlabo** [comment]
@all-contributors please add @leo6104 for code

**Comment by leo6104** [comment]
Thanks for merge this PR. :) 
I tested it on XCode Version 12.4 (12D4e) and Capacitor 3-beta.1.

**Comment by rdlabo** [comment]
It may from Capacitor 3. Thanks!

**Pull request merged**
