### PR TITLE
Limited login implementation

### PR DESCRIPTION
**Pull request by AlvinTCH**
Similar to pull request #94 , I have added my own implementation for capacitor 6, with updated readme for easier understanding This is quite urgent as limitedLogin is forced upon the current fbsdk

Let me know if the code can be improved or if the readme is unclear

### CODE REVIEW

**Comment by AlvinTCH** [comment]
I have created a [npm package](https://www.npmjs.com/package/@greytch/capacitor-facebook-login) for anyone who would like to try this implementation out

**Comment by ciccilleju** [comment]
hello @AlvinTCH , do you think this will solve my issue with iOS 
image

with version 5.0.3 everything works fine

**Comment by AlvinTCH** [comment]
@ciccilleju Do you have an issue talking to your backend to verify the token currently? I think there is a setting that is turned off by default that is related to the advertising tracker. If the advertising tracker setting is turned off, the normal facebook login will result in a invalid token, then you will need limitedLogin. Do note that you will need to change some things in your backend as well to verify the facebook limited login tokens as limitedLogin returns JWT instead of OAuth2 tokens.

**Comment by ciccilleju** [comment]
Exactly, I think the backend needs some additional adjustment because right
now it says the token isn’t valid

Thank you I will check as soon as possible

-


Il giorno gio 2 mag 2024 alle 02:23 AlvinT ***@***.***> ha
scritto:

**Comment by ciccilleju** [comment]
> @ciccilleju Do you have an issue talking to your backend to verify the token currently? I think there is a setting that is turned on by default that is related to the advertising tracker blocking for iOS. If the advertising tracker setting is turned on, the normal facebook login will result in a invalid token, then you will need the `limitedLogin` function in this implementation. Do note that you will need to change some things in your backend as well to verify the facebook limited login tokens as limitedLogin returns JWT instead of OAuth2 tokens.

there is any chance to continue using the normal login? 
because that doesn't work anymore with version 6.0.0 but works with versione 5.0.3 without changing any backend part or fe part

**Comment by AlvinTCH** [comment]
> > @ciccilleju Do you have an issue talking to your backend to verify the token currently? I think there is a setting that is turned on by default that is related to the advertising tracker blocking for iOS. If the advertising tracker setting is turned on, the normal facebook login will result in a invalid token, then you will need the `limitedLogin` function in this implementation. Do note that you will need to change some things in your backend as well to verify the facebook limited login tokens as limitedLogin returns JWT instead of OAuth2 tokens.
> 
> there is any chance to continue using the normal login? because that doesn't work anymore with version 6.0.0 but works with versione 5.0.3 without changing any backend part or fe part

unfortunately no. this is kind of forced upon us with fbsdk v17, which is the latest fbsdk that we are using with capacitor v6. unless facebook changes their decision, there isn't much we can do about it

**Comment by ciccilleju** [comment]
> > > @ciccilleju Do you have an issue talking to your backend to verify the token currently? I think there is a setting that is turned on by default that is related to the advertising tracker blocking for iOS. If the advertising tracker setting is turned on, the normal facebook login will result in a invalid token, then you will need the `limitedLogin` function in this implementation. Do note that you will need to change some things in your backend as well to verify the facebook limited login tokens as limitedLogin returns JWT instead of OAuth2 tokens.
> > 
> > 
> > there is any chance to continue using the normal login? because that doesn't work anymore with version 6.0.0 but works with versione 5.0.3 without changing any backend part or fe part
> 
> unfortunately no. this is kind of forced upon us with fbsdk v17, which is the latest fbsdk that we are using with capacitor v6. unless facebook changes their decision, there isn't much we can do about it

all clear, thank you.
If i 've understood it right this could be the FE code:
`  async fbLoginIOS(FACEBOOK_PERMISSIONS: string[]) {

    const result = await (<any>(
      FacebookLogin.limitedLogin({ permissions: FACEBOOK_PERMISSIONS, tracking: 'limited' })
    ));

    this.loginFacebook(result.authenticationToken.token, result.authenticationToken.userId, result.authenticationToken.email);
// and here calling my backend where now if its a request from a iOS device, must check a JWT token
  }




`

**Comment by AlvinTCH** [comment]
> FacebookLogin.limitedLogi

Yes the code looks correct to me. You can refer to this [link](https://developers.facebook.com/docs/facebook-login/limited-login/token/validating#signature) for more info on checking the JWT

Here is a sample python code that I was using to test this implemenation for your reference
```
import jwt
from jwt import PyJWKClient

facebook_social_token = "<facebok social token here>"

jwks_client = PyJWKClient(
    'https://limited.facebook.com/.well-known/oauth/openid/jwks/'
)
signing_key = jwks_client.get_signing_key_from_jwt(facebook_social_token)

# try to decode the facebook token
facebook_data = jwt.decode(
    facebook_social_token,
    signing_key.key,
    algorithms=["RS256"],
    iss="https://www.facebook.com",
    options={"verify_aud": False}
)
```

**Comment by MaximeSIMET** [comment]
Hi @AlvinTCH and thank you for your fork! 

I've implemented it & i'm now calling the new `limitedLogin` method. 

` await FacebookLogin.limitedLogin({ permissions: [], tracking: 'limited' })`

However, i can still see this warning from facebook 

image


Did i miss anything ? Thank you 🙏

**Comment by ciccilleju** [comment]
the message isn't a problem, it's just a "warning"
you must use the [tracking data plugin too ](https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency)

**Comment by MaximeSIMET** [comment]
@ciccilleju from what I understand, using the limited login implemented by @AlvinTCH  means you don't have to implement the tracking data plugin. 

I'd like to avoid having to ask for this authorization as well, as it may discourage our users from using this connection method.

**Comment by ciccilleju** [comment]
Yes true but you just change how you authenticate and validate the token after, in case you are using the limited login version the token is now JWT—Francesco De GiorgioTel. (+39) 349 393 21 ***@***.*** giorno 8 lug 2024, alle ore 13:35, Maxime ***@***.***> ha scritto:﻿
@ciccilleju from what I understand, using the limited login implemented by @AlvinTCH  means you don't have to implement the tracking data plugin.
I'd like to avoid having to ask for this authorization as well, as it may discourage our users from using this connection method.

**Comment by AlvinTCH** [comment]
@MaximeSIMET The message can be ignored as long as you have moved to use the limited login if you do not want to use the data tracking plugin. You can test the JWT returned with the sample python code written above to verify if this function works on your end

**Comment by reslear** [comment]
Good news @riderx
https://github.com/Cap-go/capacitor-social-login/commit/8263b3fe4529f5de6f4f950841be7ffaa37be09c at my request implemented it in a new 
plugin https://github.com/Cap-go/capacitor-social-login join the testing!

**Comment by rdlabo** [comment]
@AlvinTCH Activate maintenance on this plugin. Thank you for your contribution!

**Comment by co-dax** [comment]
> @MaximeSIMET The message can be ignored as long as you have moved to use the limited login and if you do not want to use the data tracking plugin. You can test the JWT returned with the sample python code written above to verify if this function works on your end

@MaximeSIMET Is there any way we can make that warning message disapper?

**Comment by MaximeSIMET** [comment]
> > @MaximeSIMET The message can be ignored as long as you have moved to use the limited login and if you do not want to use the data tracking plugin. You can test the JWT returned with the sample python code written above to verify if this function works on your end
> 
> @MaximeSIMET Is there any way we can make that warning message disappear?

Unfortunately, i couldn't find any way at the moment.

**Comment by co-dax** [comment]
@MaximeSIMET Thanks

**Comment by dodomui** [comment]
Is FacebookLogin.limitedLogin() merged into master? How can I use this instead?

**Comment by AlvinTCH** [comment]
> Is FacebookLogin.limitedLogin() merged into master? How can I use this instead?

If I am not wrong, my implementation was changed. Now it is integrated with the "login" function, under the "tracking" option. I haven't got time to test it though. Will probably test it next month before deprecating my fork

**Comment by ciccilleju** [comment]
@AlvinTCH

 I’ve installed the latest version (6.1.0). 
Is it normal to receive a different type of token depending on the operating system?

I thought this behavior was resolved when using the "limited" option.

Regardless, I tried both tracking: 'enabled' and tracking: 'limited', but the accessToken doesn’t change (tracking is enabled). On iOS, I receive a JWT token, while on Android, I get an OAuth2 token.

**Pull request merged**
